name: cicd-test

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:
      - name: release
        uses: actions/checkout@master

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Build and Run Tests
        run: |
          cd src/main/java/
          mvn install:install-file -Dfile=gudusoft.gsqlparser-2.0.6.5.jar -DgroupId=com -DartifactId=gudusoft -Dversion=1.1.1 -Dpackaging=jar
          mvn clean install package '-Dmaven.test.skip=true'

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

