name: cicd-test

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:       
      - name: release
        uses: actions/checkout@master
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      
      - name: Build and Run Tests
        run: mvn test --batch-mode -Dmaven.test.failure.ignore=true
        
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

